In [2]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "data"
save_df = pd.read_csv(DATA_DIR / "google_enriched_items_save.csv")
copy_df = pd.read_csv(DATA_DIR / "google_enriched_items copy.csv")

In [3]:
save_df

,item_id,genres,summary,api_found
0,0,NaN,NaN,False
1,1,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,True
2,2,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,True
3,3,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,True
4,4,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",True
...,...,...,...,...
8395,8395,Farm life,"Part memoir, part tableau, 'Corbeau' is a mult...",True
8396,8396,Farmers,"A vingt-six ans, le Morgien Marc Warnery (1797...",True
8397,8397,NaN,"Soutiens-gorge rembourrés pour fillettes, obse...",True
8398,8398,History,"For generations now, Edward W. Said's Oriental...",True
8399,8399,NaN,NaN,False

In [4]:
copy_df

,item_id,genres,summary,page_count,average_rating,api_found
0,8400,"Fables, Latin",NaN,578.0,NaN,True
1,8401,Psychology,""" Pour comprendre la psychanalyse, écrivait Fr...",786.0,NaN,True
2,8402,NaN,Delaloye l'a formulée des milliers de fois. Av...,152.0,NaN,True
3,8403,Faith,"""Pour éprouver la soif il faut être vivant"".",151.0,NaN,True
4,8404,NaN,NaN,0.0,NaN,False
...,...,...,...,...,...,...
6886,15286,NaN,NaN,0.0,NaN,False
6887,15287,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",0.0,NaN,True
6888,15288,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,210.0,NaN,True
6889,15289,NaN,Plusieurs années avant les événements de Red E...,220.0,NaN,True
6890,15290,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,NaN,True

In [5]:
empty_list = [0.0 for i in range(len(save_df))]
save_df["average_rating"] = empty_list
save_df["page_count"] = empty_list
save_df = save_df[["item_id", "genres", "summary", "page_count", "average_rating", "api_found"]]
save_df

,item_id,genres,summary,page_count,average_rating,api_found
0,0,NaN,NaN,0.0,0.0,False
1,1,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,0.0,0.0,True
2,2,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,0.0,0.0,True
3,3,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,0.0,0.0,True
4,4,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",0.0,0.0,True
...,...,...,...,...,...,...
8395,8395,Farm life,"Part memoir, part tableau, 'Corbeau' is a mult...",0.0,0.0,True
8396,8396,Farmers,"A vingt-six ans, le Morgien Marc Warnery (1797...",0.0,0.0,True
8397,8397,NaN,"Soutiens-gorge rembourrés pour fillettes, obse...",0.0,0.0,True
8398,8398,History,"For generations now, Edward W. Said's Oriental...",0.0,0.0,True
8399,8399,NaN,NaN,0.0,0.0,False

In [10]:
copy_df.columns = save_df.columns

In [11]:
final_df = pd.concat([save_df, copy_df], ignore_index=True)
final_df

,item_id,genres,summary,page_count,average_rating,api_found
0,0,NaN,NaN,0.0,0.0,False
1,1,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,0.0,0.0,True
2,2,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,0.0,0.0,True
3,3,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,0.0,0.0,True
4,4,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",0.0,0.0,True
...,...,...,...,...,...,...
15286,15286,NaN,NaN,0.0,NaN,False
15287,15287,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",0.0,NaN,True
15288,15288,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,210.0,NaN,True
15289,15289,NaN,Plusieurs années avant les événements de Red E...,220.0,NaN,True
15290,15290,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,NaN,True

In [12]:
final_df.describe()

            item_id    page_count  average_rating
count  15291.000000  14878.000000     8567.000000
mean    7645.000000    133.309047        0.081475
std     4414.275818    312.364315        0.595887
min        0.000000      0.000000        0.000000
25%     3822.500000      0.000000        0.000000
50%     7645.000000      0.000000        0.000000
75%    11467.500000    200.000000        0.000000
max    15290.000000  16495.000000        5.000000

In [15]:
final_df.genres[0]

nan

In [16]:
open_lib_df = pd.read_csv(DATA_DIR / "enriched_items_v2.csv")
open_lib_df

,Title,Author,ISBN Valid,Publisher,Subjects,i,description,pages,api_found
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,0,NaN,NaN,False
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,1,Source title: Les interactions dans l'enseigne...,288.0,True
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,2,NaN,NaN,False
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,3,NaN,NaN,False
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,4,Includes bibliographical references.,586.0,True
...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,15286,NaN,NaN,False
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,15287,NaN,NaN,False
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,15288,"Source title: Blue Lock T02 (Blue Lock, 2)",192.0,True
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,15289,NaN,NaN,True
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,15290,NaN,NaN,False

In [ ]:
for i in range(len(final_df)):
    if pd.isna(open_lib_df["pages"][i]) == False and (pd.isna(final_df["page_count"][i]) or final_df["page_count"][i] == 0.0):
        print(i, final_df["item_id"][i], open_lib_df["pages"][i])

1
4
6
8
11
24
27
34
35
36
40
41
44
45
46
48
53
65
67
68
77
78
79
80
89
91
98
100
106
118
120
127
128
131
132
138
139
151
152
153
154
155
156
158
163
167
174
182
191
192
202
209
212
213
216
221
223
229
230
232
234
235
239
240
241
242
247
248
254
255
257
258
262
263
265
266
268
270
275
276
278
279
280
283
284
285
289
290
292
296
297
299
310
312
313
315
316
318
321
323
324
331
333
335
337
342
344
347
354
358
363
366
368
369
370
374
375
378
381
383
394
395
406
414
415
417
418
424
431
455
456
459
463
464
472
480
489
500
502
531
535
536
542
543
547
554
557
561
562
563
564
566
567
573
574
577
580
583
584
585
602
604
605
606
610
611
614
617
619
620
625
627
628
630
651
653
654
656
657
661
672
673
680
681
683
685
686
691
692
698
699
703
706
712
713
715
716
717
718
720
727
728
731
734
737
741
743
744
748
751
753
755
756
758
759
766
771
778
782
790
800
803
809
821
824
827
830
846
848
851
854
857
858
859
862
863
866
868
869
870
871
872
873
877
882
891
897
900
901
907
910
912
914
917
923
924
926
927
933
938
947
950
953
955
956
957
958
959
961
962
963
968
976
977
980
981
983
992
994
1002
1007
1040
1047
1078
1084
1087
1094
1095
1100
1109
1110
1111
1114
1116
1117
1119
1120
1121
1122
1124
1125
1126
1132
1133
1135
1139
1143
1149
1150
1156
1157
1173
1174
1175
1177
1179
1180
1181
1182
1183
1185
1186
1191
1195
1199
1200
1207
1221
1222
1223
1224
1227
1228
1238
1244
1245
1246
1247
1258
1262
1263
1265
1266
1268
1269
1284
1287
1291
1297
1300
1309
1319
1320
1326
1328
1329
1333
1336
1337
1340
1341
1343
1347
1349
1350
1352
1360
1362
1365
1366
1367
1368
1372
1373
1374
1375
1379
1384
1385
1387
1388
1389
1390
1391
1392
1409
1412
1415
1418
1425
1426
1432
1433
1444
1445
1447
1451
1453
1457
1462
1473
1474
1482
1490
1498
1499
1503
1508
1511
1516
1517
1518
1523
1525
1533
1534
1538
1543
1550
1551
1553
1554
1557
1561
1565
1590
1592
1594
1595
1596
1597
1598
1599
1601
1605
1609
1615
1616
1617
1618
1619
1627
1628
1630
1632
1634
1638
1639
1640
1646
1662
1663
1665
1666
1667
1669
1670
1672
1673
1674
1676
1677
1678
1679
1680
1681
1684
1693
1697
1699
1700
1705
1707
1709
1711
1713
1716
1717
1719
1722
1723
1727
1728
1731
1734
1735
1736
1740
1744
1752
1753
1762
1763
1772
1775
1780
1782
1783
1784
1788
1790
1794
1796
1801
1802
1803
1804
1805
1806
1807
1821
1822
1831
1837
1839
1840
1841
1842
1850
1851
1854
1856
1857
1864
1872
1873
1874
1875
1877
1878
1879
1880
1881
1889
1896
1900
1901
1902
1903
1904
1907
1909
1910
1912
1913
1920
1921
1922
1923
1927
1928
1929
1933
1935
1939
1940
1941
1946
1947
1949
1952
1960
1969
1979
1980
1985
1987
1993
1995
2001
2002
2003
2005
2013
2016
2020
2026
2028
2030
2031
2033
2037
2039
2043
2050
2051
2060
2067
2071
2080
2082
2091
2095
2102
2105
2120
2122
2126
2128
2130
2131
2132
2134
2140
2144
2148
2149
2150
2152
2155
2156
2161
2166
2167
2169
2171
2173
2175
2176
2177
2178
2181
2182
2186
2189
2190
2197
2198
2203
2204
2210
2213
2215
2218
2228
2243
2256
2257
2259
2261
2262
2265
2266
2267
2268
2271
2272
2273
2275
2276
2277
2279
2280
2284
2287
2288
2289
2290
2291
2294
2295
2296
2303
2304
2307
2308
2310
2313
2320
2323
2324
2327
2342
2344
2349
2364
2366
2370
2373
2374
2376
2379
2380
2381
2382
2384
2387
2388
2390
2391
2394
2395
2398
2400
2403
2404
2405
2411
2412
2413
2415
2417
2418
2419
2421
2422
2423
2425
2428
2429
2431
2432
2434
2435
2436
2437
2439
2443
2446
2452
2456
2457
2458
2459
2462
2464
2465
2470
2484
2487
2489
2490
2497
2502
2516
2519
2521
2538
2548
2563
2573
2575
2576
2579
2581
2583
2585
2586
2591
2592
2594
2595
2597
2603
2605
2608
2617
2618
2619
2622
2626
2632
2633
2639
2643
2644
2653
2654
2655
2661
2675
2686
2703
2706
2712
2717
2718
2720
2726
2728
2729
2735
2738
2739
2750
2758
2763
2764
2765
2770
2772
2774
2775
2779
2785
2787
2790
2794
2798
2799
2800
2801
2811
2813
2814
2824
2828
2833
2839
2840
2842
2843
2844
2847
2849
2851
2854
2856
2857
2858
2859
2867
2869
2873
2894
2896
2900
2901
2903
2906
2907
2908
2909
2917
2919
2920
2921
2923
2924
2925
2926
2927
2929
2930
2944
2946
2958
2960
2963
2964
2965
2967
2968
2969
2974
2976
2977
2979
2984
2986
2988
2991
3002
3006
3009
3013
3018
3019
3037
3043
3046
3051
3052
3055
3060
3061
3062
3067
3075
3083
3087
3088
3102
3107
3110
3112
3117
3125
3126
3127
3130
3133
3134
3135
3139
3146
3158
3159
3168
3170
3175
3176
3181
3182
3197
3198
3202
3213
3214
3220
3221
3222
3240
3242
3246
3259
3261
3263
3264
3272
3275
3281
3285
3307
3308
3309
3310
3313
3314
3315
3333
3341
3356
3357
3387
3388
3397
3401
3403
3404
3405
3406
3408
3409
3410
3411
3415
3420
3422
3425
3426
3430
3431
3432
3441
3445
3446
3448
3450
3451
3458
3460
3465
3469
3470
3475
3480
3482
3489
3490
3505
3510
3513
3514
3515
3519
3535
3537
3541
3542
3555
3556
3559
3568
3569
3571
3572
3573
3588
3590
3591
3599
3635
3636
3640
3646
3648
3650
3651
3653
3654
3655
3656
3663
3665
3671
3674
3676
3683
3687
3693
3696
3714
3719
3726
3736
3737
3738
3739
3742
3744
3756
3759
3771
3775
3778
3781
3782
3788
3793
3794
3796
3798
3810
3813
3821
3828
3832
3833
3837
3843
3849
3850
3851
3852
3854
3855
3856
3861
3862
3864
3866
3867
3874
3875
3876
3877
3878
3880
3883
3885
3886
3887
3892
3898
3909
3921
3931
3933
3942
3943
3945
3948
3950
3951
3954
3955
3956
3961
3969
3971
3973
3975
3976
3977
3978
3980
3982
3988
3993
3994
3997
3999
4000
4016
4018
4019
4021
4022
4023
4025
4026
4027
4028
4029
4030
4031
4032
4033
4034
4041
4042
4047
4054
4057
4058
4065
4068
4070
4072
4074
4079
4080
4081
4082
4083
4085
4086
4088
4090
4094
4098
4102
4103
4108
4116
4124
4125
4126
4127
4133
4140
4145
4149
4150
4151
4152
4154
4164
4171
4172
4174
4175
4177
4179
4182
4186
4188
4189
4191
4198
4202
4207
4225
4226
4249
4252
4254
4258
4272
4274
4275
4280
4281
4283
4284
4285
4286
4292
4303
4304
4307
4309
4314
4318
4330
4333
4336
4337
4338
4341
4345
4350
4351
4353
4357
4358
4359
4360
4361
4367
4368
4370
4373
4376
4382
4383
4386
4388
4403
4408
4410
4412
4419
4420
4426
4432
4437
4439
4444
4445
4446
4447
4451
4453
4458
4460
4463
4466
4470
4476
4497
4499
4508
4514
4515
4520
4523
4524
4525
4526
4527
4528
4529
4530
4534
4535
4536
4538
4540
4542
4545
4546
4550
4551
4553
4561
4562
4563
4567
4572
4578
4580
4581
4582
4584
4585
4586
4587
4593
4595
4598
4610
4612
4613
4615
4616
4617
4623
4628
4629
4633
4634
4635
4636
4638
4666
4667
4670
4671
4673
4674
4675
4680
4682
4684
4696
4697
4698
4699
4700
4701
4706
4707
4708
4709
4713
4718
4723
4726
4727
4728
4730
4731
4737
4742
4743
4747
4748
4753
4754
4756
4765
4781
4783
4785
4787
4793
4794
4798
4800
4801
4802
4803
4805
4806
4807
4809
4817
4820
4822
4836
4837
4842
4845
4849
4851
4852
4853
4854
4858
4867
4868
4869
4870
4871
4872
4875
4878
4890
4895
4896
4900
4901
4902
4927
4934
4935
4939
4941
4943
4947
4948
4949
4955
4956
4957
4959
4960
4961
4962
4964
4965
4966
4967
4971
4973
5004
5005
5006
5007
5008
5010
5011
5013
5017
5023
5026
5039
5053
5058
5059
5072
5105
5111
5113
5114
5126
5129
5130
5131
5132
5136
5137
5138
5140
5143
5144
5147
5154
5157
5158
5163
5171
5174
5177
5178
5179
5180
5181
5183
5191
5199
5200
5201
5204
5205
5206
5212
5219
5225
5227
5231
5233
5236
5238
5239
5242
5243
5244
5245
5246
5248
5249
5251
5254
5255
5256
5259
5260
5262
5263
5264
5266
5267
5268
5270
5271
5276
5282
5283
5284
5285
5286
5287
5289
5290
5293
5296
5297
5302
5307
5310
5312
5316
5317
5318
5319
5320
5321
5325
5326
5328
5332
5334
5336
5340
5341
5345
5349
5350
5353
5354
5355
5365
5366
5368
5371
5372
5373
5377
5378
5380
5381
5383
5384
5385
5390
5395
5396
5399
5410
5415
5416
5418
5426
5428
5434
5437
5440
5442
5443
5444
5445
5446
5452
5454
5463
5464
5468
5469
5472
5473
5474
5476
5478
5481
5482
5483
5486
5492
5495
5496
5500
5509
5525
5527
5529
5534
5537
5538
5540
5541
5561
5580
5581
5582
5590
5592
5595
5598
5600
5602
5613
5614
5615
5619
5622
5625
5629
5637
5639
5640
5641
5643
5644
5645
5646
5647
5649
5650
5652
5653
5654
5655
5657
5660
5662
5663
5664
5666
5667
5668
5672
5674
5675
5678
5685
5687
5691
5693
5694
5695
5696
5700
5701
5703
5706
5708
5709
5710
5711
5712
5713
5714
5719
5721
5722
5725
5726
5728
5739
5743
5745
5748
5753
5754
5755
5761
5762
5765
5768
5774
5782
5795
5796
5797
5799
5801
5802
5807
5809
5810
5827
5841
5845
5846
5849
5850
5851
5853
5867
5872
5878
5879
5880
5881
5884
5885
5887
5889
5891
5896
5897
5900
5901
5903
5904
5907
5909
5912
5913
5914
5916
5917
5918
5919
5920
5922
5923
5927
5929
5930
5934
5938
5940
5942
5950
5953
5955
5957
5958
5963
5965
5967
5968
5969
5970
5972
5973
5975
5978
5982
5983
5986
5987
5988
5995
5998
6006
6012
6015
6016
6018
6036
6040
6045
6052
6055
6056
6057
6061
6062
6067
6069
6070
6072
6077
6079
6082
6083
6085
6086
6089
6090
6091
6093
6094
6098
6103
6104
6106
6115
6118
6119
6122
6123
6125
6130
6131
6132
6134
6136
6137
6139
6140
6143
6146
6147
6148
6149
6150
6151
6152
6153
6154
6156
6159
6161
6162
6163
6166
6168
6170
6171
6172
6173
6174
6175
6182
6187
6189
6190
6191
6192
6193
6196
6202
6206
6208
6218
6220
6224
6226
6227
6228
6231
6233
6234
6235
6240
6241
6245
6246
6250
6251
6252
6253
6267
6268
6270
6273
6274
6276
6277
6278
6279
6280
6282
6283
6287
6288
6291
6294
6298
6305
6315
6317
6327
6330
6331
6333
6334
6339
6351
6352
6369
6371
6380
6390
6391
6392
6393
6394
6395
6396
6398
6399
6400
6402
6403
6404
6407
6414
6417
6423
6427
6429
6434
6448
6449
6453
6457
6459
6461
6462
6464
6465
6467
6478
6479
6481
6483
6485
6487
6488
6490
6496
6497
6501
6503
6505
6506
6509
6512
6515
6522
6535
6539
6540
6541
6543
6545
6554
6555
6558
6566
6573
6574
6575
6582
6583
6589
6597
6598
6602
6605
6612
6613
6616
6618
6620
6625
6626
6627
6630
6631
6632
6633
6638
6648
6652
6655
6658
6661
6662
6663
6664
6667
6668
6669
6673
6674
6675
6680
6687
6692
6694
6697
6699
6700
6702
6703
6706
6715
6719
6721
6723
6728
6731
6733
6734
6737
6738
6740
6742
6744
6748
6749
6750
6751
6752
6754
6756
6757
6758
6759
6761
6762
6763
6764
6769
6770
6771
6772
6774
6777
6779
6780
6781
6782
6783
6785
6791
6800
6803
6807
6808
6813
6818
6820
6822
6825
6827
6835
6836
6837
6838
6839
6842
6843
6844
6845
6848
6849
6855
6869
6876
6877
6884
6885
6886
6887
6894
6898
6902
6903
6905
6907
6909
6910
6922
6923
6926
6933
6936
6938
6942
6944
6946
6952
6968
6971
6976
6978
6984
6993
6995
6997
7002
7004
7007
7008
7010
7013
7015
7019
7020
7024
7025
7026
7028
7030
7039
7040
7041
7046
7049
7050
7052
7054
7055
7062
7064
7069
7082
7083
7091
7093
7099
7100
7103
7104
7106
7107
7109
7110
7111
7116
7118
7120
7122
7123
7124
7125
7127
7129
7130
7131
7141
7147
7155
7159
7161
7162
7164
7166
7169
7172
7173
7175
7176
7177
7181
7201
7213
7219
7221
7223
7224
7230
7231
7235
7237
7239
7240
7246
7248
7251
7252
7253
7254
7257
7258
7259
7260
7261
7262
7264
7281
7295
7296
7302
7313
7314
7316
7321
7331
7334
7335
7340
7341
7342
7343
7344
7346
7350
7354
7355
7359
7362
7368
7370
7373
7375
7382
7388
7393
7398
7401
7405
7406
7407
7408
7409
7410
7425
7430
7432
7437
7451
7456
7461
7465
7466
7468
7470
7471
7473
7475
7476
7477
7478
7484
7489
7490
7495
7513
7524
7526
7529
7530
7532
7534
7535
7536
7538
7539
7540
7541
7544
7545
7553
7555
7557
7568
7571
7572
7573
7575
7577
7580
7584
7586
7587
7588
7590
7591
7594
7597
7599
7601
7602
7603
7607
7608
7617
7620
7623
7624
7625
7626
7628
7629
7631
7632
7634
7637
7639
7640
7641
7642
7643
7647
7650
7651
7654
7656
7658
7659
7661
7663
7664
7665
7667
7672
7674
7675
7677
7682
7688
7696
7697
7699
7704
7706
7710
7711
7712
7713
7715
7717
7718
7719
7722
7723
7731
7744
7745
7746
7755
7763
7768
7773
7781
7783
7796
7797
7801
7803
7805
7807
7809
7810
7812
7813
7814
7815
7826
7842
7843
7844
7846
7849
7851
7852
7855
7856
7857
7858
7864
7865
7866
7869
7870
7875
7876
7877
7881
7882
7883
7886
7888
7891
7895
7897
7898
7900
7902
7914
7915
7917
7918
7919
7924
7929
7934
7935
7937
7939
7940
7942
7943
7944
7945
7947
7949
7950
7951
7952
7953
7954
7964
7966
7967
7970
7974
7976
7977
7978
7979
7981
7982
7983
7987
7990
7995
7996
7998
7999
8000
8003
8004
8005
8007
8009
8011
8012
8016
8022
8023
8025
8029
8030
8032
8033
8036
8037
8038
8040
8041
8042
8043
8051
8055
8058
8059
8060
8062
8076
8079
8087
8095
8100
8102
8110
8115
8116
8117
8120
8122
8124
8125
8129
8131
8133
8134
8135
8138
8143
8144
8147
8148
8150
8153
8155
8157
8158
8161
8165
8173
8174
8175
8182
8184
8185
8190
8192
8195
8201
8203
8205
8206
8209
8210
8219
8221
8222
8227
8231
8233
8235
8237
8238
8239
8241
8243
8246
8251
8255
8256
8257
8259
8261
8267
8269
8272
8278
8281
8282
8288
8298
8300
8301
8304
8305
8313
8315
8318
8324
8326
8328
8330
8331
8332
8338
8340
8343
8344
8351
8352
8353
8354
8359
8362
8366
8372
8373
8379
8384
8387
8389
8396
8398
8422
8445
8460
8464
8471
8480
8482
8571
8589
8590
8675
8716
8726
8745
8748
8774
8780
8800
8808
8839
8861
8872
8884
8892
8905
8918
8933
8951
8957
8971
8999
9052
9054
9056
9098
9119
9147
9161
9162
9174
9203
9240
9255
9258
9310
9380
9508
9563
9589
9594
9610
9613
9633
9694
9697
9715
9717
9719
9726
9730
9775
9781
9811
9820
9838
9880
9881
9882
9895
9913
9950
9961
10005
10014
10016
10026
10030
10033
10052
10111
10118
10124
10169
10170
10208
10222
10223
10226
10250
10286
10290
10297
10304
10313
10331
10370
10394
10396
10400
10405
10406
10430
10435
10443
10458
10459
10475
10476
10525
10581
10628
10648
10846
10902
10949
10960
10966
10970
10973
10980
11031
11116
11167
11181
11193
11216
11292
11293
11299
11306
11308
11311
11314
11341
11353
11432
11438
11444
11486
11502
11521
11535
11539
11556
11568
11576
11583
11590
11592
11614
11651
11709
11730
11745
11769
11779
11829
11855
11877
11912
11928
11996
12033
12094
12113
12114
12115
12119
12120
12158
12160
12168
12216
12237
12326
12368
12436
12454
12463
12468
12478
12481
12491
12513
12549
12557
12567
12575
12665
12672
12681
12682
12683
12689
12694
12832
12845
12869
12876
12879
12890
12900
12916
12945
12946
12957
12971
12979
12985
13079
13113
13129
13171
13213
13216
13254
13281
13285
13303
13353
13356
13366
13373
13386
13445
13447
13482
13494
13504
13543
13547
13550
13555
13625
13676
13686
13701
13744
13747
13748
13751
13774
13865
13882
13895
13918
13942
14012
14038
14080
14097
14133
14142
14150
14162
14165
14182
14195
14244
14249
14274
14293
14301
14356
14360
14366
14376
14408
14419
14433
14452
14463
14473
14475
14495
14514
14533
14584
14639
14646
14663
14669
14675
14679
14773
14793
14811
14824
14829
14832
14855
14862
14880
14922
14930
14934
14956
14967
15011
15060
15067
15081
15118
15128
15177
15186
15194
15235
15236
15255
15276

In [20]:
open_lib_df["description"] = final_df["summary"]
open_lib_df["genres"] = final_df["genres"]

In [24]:
for i in range(len(final_df)):
    if pd.isna(open_lib_df["pages"][i]) and (pd.isna(final_df["page_count"][i])==False) and final_df["page_count"][i] != 0.0:
        print(i, final_df["page_count"][i], open_lib_df["pages"][i])
        open_lib_df["pages"][i] = final_df["page_count"][i]

open_lib_df

,Title,Author,ISBN Valid,Publisher,Subjects,i,description,pages,api_found,genres
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,0,NaN,NaN,False,NaN
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,1,C'est dans l'interaction en classe que s'actua...,288.0,True,Interaction analysis in education
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,2,Depuis la parution en 1918 de l'ouvrage fondat...,NaN,False,Narrative inquiry (Research method)
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,3,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,False,NaN
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,4,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,True,French literature
...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,15286,NaN,NaN,False,NaN
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,15287,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,False,NaN
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,15288,After a disastrous defeat at the 2018 World Cu...,192.0,True,Comics & Graphic Novels
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,15289,Plusieurs années avant les événements de Red E...,220.0,True,NaN
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,15290,Analyse: Mandat de la ville de Lausanne pour l...,NaN,False,NaN

In [25]:
open_lib_df.columns

Index(['Title', 'Author', 'ISBN Valid', 'Publisher', 'Subjects', 'i',
       'description', 'pages', 'api_found', 'genres'],
      dtype='object')

In [26]:
open_lib_df = open_lib_df[['Title', 'Author', 'ISBN Valid', 'Publisher', 'Subjects', 'genres', 'description', 'pages', 'i', 'api_found']]
open_lib_df

,Title,Author,ISBN Valid,Publisher,Subjects,genres,description,pages,i,api_found
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,NaN,NaN,NaN,0,False
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,288.0,1,True
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,2,False
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,3,False
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,4,True
...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,NaN,NaN,NaN,15286,False
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,15287,False
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,192.0,15288,True
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,NaN,Plusieurs années avant les événements de Red E...,220.0,15289,True
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,15290,False

In [30]:
open_lib_df.columns = ['Title', 'Author', 'ISBN Valid', 'Publisher', 'Subjects', 'summary', 'description', 'pages', 'i', 'api_found']
open_lib_df.to_csv(DATA_DIR / "enriched_items_v3.csv", index=False)

In [32]:
final_df["api_found"].value_counts()

api_found
True     12423
False     2868
Name: count, dtype: int64

In [33]:
import numpy as np
for i in range(len(open_lib_df)):
    if open_lib_df["pages"][i] == 0.0:
        open_lib_df["pages"][i] = np.nan

In [35]:
open_lib_df.to_csv(DATA_DIR / "enriched_items_v3.csv", index=False)

In [36]:
open_lib_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15291 entries, 0 to 15290
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        15291 non-null  object
 1   Author       12638 non-null  object
 2   ISBN Valid   14568 non-null  object
 3   Publisher    15266 non-null  object
 4   Subjects     13068 non-null  object
 5   summary      8369 non-null   object
 6   description  10715 non-null  object
 7   pages        8219 non-null   float64
 8   i            15291 non-null  int64
 9   api_found    15291 non-null  bool
dtypes: bool(1), float64(1), int64(1), object(7)
memory usage: 1.1+ MB

In [37]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15291 entries, 0 to 15290
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   item_id         15291 non-null  int64
 1   genres          8369 non-null   object
 2   summary         10715 non-null  object
 3   page_count      14878 non-null  float64
 4   average_rating  8567 non-null   float64
 5   api_found       15291 non-null  bool
dtypes: bool(1), float64(2), int64(1), object(2)
memory usage: 612.4+ KB

In [38]:
df = pd.read_csv(DATA_DIR / "enriched_items_merge_openlibrary_googlebooksAPI.csv")
df

,Title,Author,ISBN Valid,Publisher,Subjects,description,summary,pages,i,api_found
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,NaN,NaN,NaN,0,False
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,288.0,1,True
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,2,False
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,3,False
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,4,True
...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,NaN,NaN,NaN,15286,False
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,15287,False
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,192.0,15288,True
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,NaN,Plusieurs années avant les événements de Red E...,220.0,15289,True
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,15290,False

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15291 entries, 0 to 15290
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        15291 non-null  object
 1   Author       12638 non-null  object
 2   ISBN Valid   14568 non-null  object
 3   Publisher    15266 non-null  object
 4   Subjects     13068 non-null  object
 5   description  8369 non-null   object
 6   summary      10715 non-null  object
 7   pages        8219 non-null   float64
 8   i            15291 non-null  int64
 9   api_found    15291 non-null  bool
dtypes: bool(1), float64(1), int64(1), object(7)
memory usage: 1.1+ MB

In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "data"
ENRICHED_ITEMS_PATH = DATA_DIR / "enriched_items_merge_openlibrary_googlebooksAPI.csv" 
google_Path = DATA_DIR / "google_enriched_items.csv" 

final_df = pd.read_csv(ENRICHED_ITEMS_PATH)
google_df = pd.read_csv(google_Path)

In [2]:
final_df

,Title,Author,ISBN Valid,Publisher,Subjects,description,summary,pages,i,api_found
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,NaN,NaN,NaN,0,False
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,288.0,1,True
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,2,False
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,3,False
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,4,True
...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,NaN,NaN,NaN,15286,False
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,15287,False
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,192.0,15288,True
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,NaN,Plusieurs années avant les événements de Red E...,220.0,15289,True
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,15290,False

In [3]:
google_df

,item_id,genres,summary,page_count,average_rating,api_found
0,0,NaN,NaN,NaN,NaN,False
1,1,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,True,NaN,NaN
2,2,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,NaN,True
3,3,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,True,NaN,NaN
4,4,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",True,NaN,NaN
...,...,...,...,...,...,...
15286,15286,NaN,NaN,0.0,NaN,False
15287,15287,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",0.0,NaN,True
15288,15288,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,210.0,NaN,True
15289,15289,NaN,Plusieurs années avant les événements de Red E...,220.0,NaN,True
15290,15290,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,NaN,True

In [5]:
google_df.columns

Index(['item_id', ' genres', ' summary', ' page_count', ' average_rating',
       ' api_found'],
      dtype='str')

In [6]:
final_df["genres"] = google_df[" genres"]
final_df.columns

Index(['Title', 'Author', 'ISBN Valid', 'Publisher', 'Subjects', 'description',
       'summary', 'pages', 'i', 'api_found', 'genres'],
      dtype='str')

In [7]:
final_df = final_df[['Title', 'Author', 'ISBN Valid', 'Publisher', 'Subjects', 'description', 'genres', 'summary', 'pages', 'i', 'api_found']]
final_df

,Title,Author,ISBN Valid,Publisher,Subjects,description,genres,summary,pages,i,api_found
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,NaN,NaN,NaN,NaN,0,False
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,Interaction analysis in education,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,288.0,1,True
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,Narrative inquiry (Research method),Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,2,False
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,NaN,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,3,False
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,French literature,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,4,True
...,...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,NaN,NaN,NaN,NaN,15286,False
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,NaN,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,15287,False
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,Comics & Graphic Novels,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,192.0,15288,True
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,NaN,NaN,Plusieurs années avant les événements de Red E...,220.0,15289,True
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,NaN,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,15290,False

In [13]:
final_df.pages.describe()

count     8219.000000
mean       373.915318
std        441.153831
min          1.000000
25%        183.000000
50%        276.000000
75%        425.000000
max      16495.000000
Name: pages, dtype: float64

In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "data"

df = pd.read_csv(DATA_DIR / "full_item_dataset.csv")
df

,item_id,genres,summary,page_count,average_rating,cover_url,api_found
0,0,NaN,NaN,0.0,NaN,NaN,False
1,1,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,287.0,NaN,NaN,True
2,2,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,311.0,NaN,http://books.google.com/books/content?id=Q2PMD...,True
3,3,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,0.0,NaN,NaN,True
4,4,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,NaN,http://books.google.com/books/content?id=f5u3z...,True
...,...,...,...,...,...,...,...
10295,10295,NaN,NaN,NaN,NaN,NaN,False
10296,10296,NaN,NaN,NaN,NaN,NaN,False
10297,10297,NaN,NaN,NaN,NaN,NaN,False
10298,10298,NaN,NaN,NaN,NaN,NaN,False
10299,10299,NaN,NaN,NaN,NaN,NaN,False

In [8]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parent / "data"
df = pd.read_csv(DATA_DIR / "enriched_items_merge_openlibrary_googlebooksAPI.csv")
df

,Title,Author,ISBN Valid,Publisher,Subjects,genres,summary,page_count,i,api_found,cover_url
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,NaN,NaN,NaN,0,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,288.0,1,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,2,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,3,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
4,Les années glorieuses : roman /,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,4,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
...,...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo /,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,NaN,NaN,NaN,15286,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15287,God of high school : le match contre les dieux /,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,15287,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15288,Blue Lock /,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,192.0,15288,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15289,Red eyes sword : akame ga kill ! Zero /,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,NaN,Plusieurs années avant les événements de Red E...,220.0,15289,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,15290,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg

In [6]:
df["cover_url"] = ["https://cdnattic.atticbooks.co.ke/img/Z665993.jpg" for i in range(len(df))]

In [17]:
df.to_csv(DATA_DIR / "enriched_items_merge_openlibrary_googlebooksAPI.csv", index=False)

In [15]:
liste = []
for i in range(len(df)):
    title = df["Title"][i]
    if " /" in title:
        liste.append(title[:-2])
    else:
        liste.append(title)
df["Title"] = liste
df

,Title,Author,ISBN Valid,Publisher,Subjects,genres,summary,page_count,i,api_found,cover_url
0,Classification décimale universelle : édition ...,NaN,9782871303336; 2871303339,Ed du CEFAL,Classification décimale universelle; Indexatio...,NaN,NaN,NaN,0,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
1,Les interactions dans l'enseignement des langu...,"Cicurel, Francine, 1947-",9782278058327; 2278058320,Didier,didactique--langue étrangère - enseignement; d...,Interaction analysis in education,C'est dans l'interaction en classe que s'actua...,288.0,1,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
2,Histoire de vie et recherche biographique : pe...,NaN,2343190194; 9782343190198,L'Harmattan,Histoires de vie en sociologie; Sciences socia...,Narrative inquiry (Research method),Depuis la parution en 1918 de l'ouvrage fondat...,NaN,2,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
3,Ce livre devrait me permettre de résoudre le c...,"Mazas, Sylvain, 1980-",9782365350020; 236535002X; 9782365350488; 2365...,Vraoum!,Moyen-Orient; Bandes dessinées autobiographiqu...,NaN,Tome 1: Suite à un voyage humanitaire au Liban...,NaN,3,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
4,Les années glorieuses : roman,"Lemaitre, Pierre, 1951-",9782702180815; 2702180817; 9782702183618; 2702...,Calmann-Lévy,France--1945-1975; Roman historique; Roman fra...,French literature,"Trois histoires d'amour, un lanceur d'alerte, ...",586.0,4,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
...,...,...,...,...,...,...,...,...,...,...,...
15286,Le vagabond de Tokyo,"Fukutani, Takashi, 1952-2000",9782353480111; 235348011X; 9782353480241; 2353...,Le Lézard noir,Mangas,NaN,NaN,NaN,15286,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15287,God of high school : le match contre les dieux,"Park, Yong-Je",9782382880203; 2382880201; 9782382880210; 2382...,Kbooks,NaN,NaN,"Jin Mori, 17 ans, est invité à un tournoi d'ar...",NaN,15287,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15288,Blue Lock,"Kaneshiro, Muneyuki",9782811650254; 2811650253; 9782811661274; 2811...,Pika,Compétitions; Football; Entraînement (sports);...,Comics & Graphic Novels,After a disastrous defeat at the 2018 World Cu...,192.0,15288,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15289,Red eyes sword : akame ga kill ! Zero,Takahiro,9782368522134; 2368522131; 9782368522141; 2368...,Kurokawa,Bandes dessinées; Mangas,NaN,Plusieurs années avant les événements de Red E...,220.0,15289,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg
15290,Directives de projet applicables à l'étude et ...,NaN,NaN,Commune de Lausanne,école (bâtiment) - construction - planificatio...,NaN,Analyse: Mandat de la ville de Lausanne pour l...,NaN,15290,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg,https://cdnattic.atticbooks.co.ke/img/Z665993.jpg

In [16]:
df["Title"][2]

'Histoire de vie et recherche biographique : perspectives sociohistoriques'